name: Deploy

# Ensure that this workflow runs on pushes to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Step to checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3  # Use the latest version of actions

      # Set up Node.js environment using the latest stable version
      - name: Setup Node.js
        uses: actions/setup-node@v3  # Use the latest version
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm ci  # You can use npm ci if you have a package-lock.json

      # Build the project
      - name: Build project
        run: npm run build

      # Upload build artifacts
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3  # Use the latest version
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # Download the artifact from the build job
      - name: Download artifact
        uses: actions/download-artifact@v3  # Use the latest version
        with:
          name: production-files
          path: ./dist

      # Deploy to GitHub Pages using peaceiris/actions-gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
